//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public Nullable<int> Order_CusID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Order_Phone { get; set; }
        public string Order_Address { get; set; }
        public string Order_Detail { get; set; }
        public Nullable<double> Order_SubTotal { get; set; }
        public Nullable<double> Order_Discount { get; set; }
        public Nullable<double> Order_ShipFee { get; set; }
        public Nullable<double> Order_Total { get; set; }
        public Nullable<int> Order_ProDeID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
