//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ProDe_ID { get; set; }
        public string ProDe_SKU { get; set; }
        public Nullable<int> ProDe_Quantity { get; set; }
        public string ProDe_Detail { get; set; }
        public Nullable<bool> ProDe_Status { get; set; }
        public string ProDe_Image { get; set; }
        public Nullable<int> ProDe_SoldCount { get; set; }
        public Nullable<int> ProDe_CateID { get; set; }
        public Nullable<int> ProDe_SupplierID { get; set; }
        public Nullable<int> ProDe_AuthorID { get; set; }
        public Nullable<int> ProDe_PublisherID { get; set; }
        public Nullable<int> ProDe_VoucherID { get; set; }
        public string ProDe_YearOfPublish { get; set; }
        public string ProDe_Language { get; set; }
        public Nullable<int> ProDe_Weight { get; set; }
        public string ProDe_Size { get; set; }
        public Nullable<int> ProDe_NumOfPage { get; set; }
        public string ProDe_Form { get; set; }
        public Nullable<int> ProDe_ProductID { get; set; }
        public Nullable<int> ProDe_TranslatorID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Product Product { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Translator Translator { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
